package contextengine

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/RhyChaw/aurium/internal/gitx"
	"github.com/RhyChaw/aurium/internal/stack"
	"github.com/RhyChaw/aurium/internal/store"
)

// ProjectionFile is where the generated context lands inside a worktree.
//
// It is written by the host into the bind mount, and .aurium/ is git-excluded,
// so it reaches the agent without ever appearing in a diff or a PR.
const ProjectionFile = "CONTEXT.md"

// ProjectionPath returns the projection path for a worktree.
func ProjectionPath(worktree string) string {
	return filepath.Join(worktree, gitx.AuriumDir, ProjectionFile)
}

// ProjectionData is everything the projection needs, gathered by the caller so
// rendering itself is pure and testable.
type ProjectionData struct {
	Container store.Container
	Task      store.Task
	Agents    []store.Agent

	Objective   string
	Constraints string
	Decisions   []Item
	Discoveries []Item

	// SyncStatus is recomputed from git, so the agent is told the truth about
	// its position rather than a possibly stale stored status. It is display
	// text; behaviour keys off Stale, never off matching this string.
	SyncStatus string
	// Stale means the parent has moved. It is a separate flag rather than a
	// comparison against SyncStatus, because SyncStatus carries human detail
	// ("stale — parent is 3 commits ahead") that no equality check will match.
	Stale      bool
	ParentDesc string

	UnreadMessages int
	Tools          []string
}

// Render produces the §8.5 CONTEXT.md.
//
// The tone is deliberate: this file is read by a language model on every turn,
// so it states facts and rules plainly and stays short. Anything vague here
// costs tokens on every single turn of every agent.
func Render(d ProjectionData) []byte {
	var b strings.Builder

	title := d.Task.Title
	if title == "" {
		title = d.Container.Branch
	}
	fmt.Fprintf(&b, "# Aurium container %s — %s\n\n", d.Container.ID, title)
	b.WriteString("<!-- Generated by auriumd. Do not edit: it is regenerated whenever\n" +
		"     this container's context changes. Change it through the aurium_context_*\n" +
		"     tools instead, which version and permission every write. -->\n\n")

	section := func(heading, body, note string) {
		fmt.Fprintf(&b, "## %s\n", heading)
		if strings.TrimSpace(body) == "" {
			fmt.Fprintf(&b, "_%s_\n\n", note)
			return
		}
		b.WriteString(strings.TrimRight(body, "\n") + "\n\n")
	}

	section("Objective", d.Objective, "not set — ask, or set it with aurium_context_write(\"task/objective\")")
	section("Constraints", d.Constraints, "none recorded")

	fmt.Fprintf(&b, "## Stack position\n")
	fmt.Fprintf(&b, "- branch: `%s`\n", d.Container.Branch)
	fmt.Fprintf(&b, "- parent: %s\n", d.ParentDesc)
	fmt.Fprintf(&b, "- base:   `%s`\n", short(d.Container.BaseSHA))
	fmt.Fprintf(&b, "- status: %s\n", d.SyncStatus)
	if d.Stale {
		b.WriteString("- your parent has moved. Run `aurium sync` (or ask the human to) " +
			"before building on top of stale work.\n")
	}
	b.WriteString("\n")

	writeItems(&b, "Decisions", d.Decisions,
		"none recorded — record them with aurium_context_append(\"decisions/<slug>\", ...)")
	writeItems(&b, "Discoveries", d.Discoveries,
		"none recorded")

	fmt.Fprintf(&b, "## Inbox\n")
	switch d.UnreadMessages {
	case 0:
		b.WriteString("No unread messages.\n\n")
	case 1:
		b.WriteString("1 unread message — call `aurium_ipc_inbox`.\n\n")
	default:
		fmt.Fprintf(&b, "%d unread messages — call `aurium_ipc_inbox`.\n\n", d.UnreadMessages)
	}

	// The environment rule is the single most important thing an agent must
	// know about this system, because violating it loses work silently: an
	// ad-hoc install survives until the next --env sync and then vanishes.
	b.WriteString("## Environment rule\n")
	b.WriteString("This container's environment is **re-derived**, not patched, on " +
		"`sync --env` and on restore. Anything you install ad hoc will be lost.\n")
	b.WriteString("Declare installs in `aurium.yaml` under `hooks.post_create` — that file " +
		"is in source, so it survives.\n\n")

	b.WriteString("## Your branch\n")
	fmt.Fprintf(&b, "You may commit only to `%s`. Attempts to move any other branch are "+
		"refused by a git hook, by design: other containers are relying on their own branches.\n\n",
		d.Container.Branch)

	if len(d.Tools) > 0 {
		b.WriteString("## Tools\n")
		for _, t := range d.Tools {
			fmt.Fprintf(&b, "- `%s`\n", t)
		}
		b.WriteString("\n")
	}
	return []byte(b.String())
}

func writeItems(b *strings.Builder, heading string, items []Item, empty string) {
	fmt.Fprintf(b, "## %s\n", heading)
	if len(items) == 0 {
		fmt.Fprintf(b, "_%s_\n\n", empty)
		return
	}
	for _, it := range items {
		fmt.Fprintf(b, "### %s (v%d)\n%s\n\n", it.Key, it.Version, strings.TrimRight(it.Content, "\n"))
	}
}

// Gather collects the data for a container's projection.
func (e *Engine) Gather(ctx context.Context, containerID string, tools []string) (ProjectionData, error) {
	c, err := e.Store.GetContainer(ctx, containerID)
	if err != nil {
		return ProjectionData{}, err
	}

	d := ProjectionData{Container: c, Tools: tools}

	if c.TaskID != "" {
		if t, err := e.Store.GetTask(ctx, c.TaskID); err == nil {
			d.Task = t
		}
	}
	d.Agents, _ = e.Store.ListAgents(ctx, containerID)

	get := func(key string) string {
		// Container scope shadows project scope on key collision (§8.1).
		if it, err := e.Get(ctx, Ref{Scope: ScopeContainer, ScopeID: containerID, Key: key}); err == nil {
			return it.Content
		}
		if it, err := e.Get(ctx, Ref{Scope: ScopeProject, ScopeID: c.ProjectID, Key: key}); err == nil {
			return it.Content
		}
		return ""
	}
	d.Objective = get("task/objective")
	d.Constraints = get("task/constraints")

	d.Decisions = e.recent(ctx, c, "decisions/", 10)
	d.Discoveries = e.recent(ctx, c, "discoveries/", 10)

	d.ParentDesc = c.ParentBranch
	if c.ParentContainerID != "" {
		if p, err := e.Store.GetContainer(ctx, c.ParentContainerID); err == nil {
			d.ParentDesc = fmt.Sprintf("`%s` (%s)", p.Branch, p.ID)
		}
	} else {
		d.ParentDesc = fmt.Sprintf("`%s` (the base branch)", c.ParentBranch)
	}

	// Recompute from git: a stored status can be seconds out of date, and this
	// text is what the agent will act on.
	if res, err := stack.CheckEligibility(ctx, gitx.New(c.Worktree), stack.Target{
		Branch: c.Branch, ParentBranch: c.ParentBranch, BaseSHA: c.BaseSHA,
	}); err == nil {
		d.SyncStatus = string(res.Eligibility)
		if res.Eligibility == stack.Eligible {
			d.Stale = true
			d.SyncStatus = fmt.Sprintf("stale — parent is %d commit(s) ahead", res.Behind)
		}
	} else {
		d.SyncStatus = c.Status
	}

	e.Store.DB().QueryRowContext(ctx,
		`SELECT count(*) FROM messages WHERE to_container_id = ? AND status != 'acked'`,
		containerID).Scan(&d.UnreadMessages)

	return d, nil
}

// recent returns the most recently updated items under a prefix, from both the
// container's own scope and the project scope.
func (e *Engine) recent(ctx context.Context, c store.Container, prefix string, limit int) []Item {
	rows, err := e.Store.DB().QueryContext(ctx,
		`SELECT id, scope, scope_id, key, version, content, mime, updated_by, updated_at
		 FROM context_items
		 WHERE key LIKE ?
		   AND ((scope = 'container' AND scope_id = ?) OR (scope = 'project' AND scope_id = ?))
		 ORDER BY updated_at DESC LIMIT ?`,
		prefix+"%", c.ID, c.ProjectID, limit)
	if err != nil {
		return nil
	}
	defer rows.Close()

	var out []Item
	for rows.Next() {
		var it Item
		if err := rows.Scan(&it.ID, &it.Scope, &it.ScopeID, &it.Key, &it.Version,
			&it.Content, &it.MIME, &it.UpdatedBy, &it.UpdatedAt); err != nil {
			return out
		}
		out = append(out, it)
	}
	return out
}

// WriteProjection regenerates a container's CONTEXT.md.
//
// The write is atomic (temp file plus rename) because an agent may read this
// file at any instant; a half-written projection would be worse than a stale
// one.
func (e *Engine) WriteProjection(ctx context.Context, containerID string, tools []string) error {
	d, err := e.Gather(ctx, containerID, tools)
	if err != nil {
		return err
	}
	path := ProjectionPath(d.Container.Worktree)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, Render(d), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func short(sha string) string {
	if len(sha) > 8 {
		return sha[:8]
	}
	return sha
}
